title: HMM-UNPAM # your site title
author: I V Agung Eko Priyono
email: iv.agung.ep@hmm-unpam.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Himpunan Mahasiswa Manajemen Universitas Pamulang.
  Situs resmi HMM-UNPAM.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://hmm-unpam.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hmm_unpam # replace with your_twitter_username or comment to remove link from footer
github_username: hmm.unpam  # replace with your_github_username or comment to remove link from footer
instagram_username: hmm_unpam # replace with your_instagram_username or comment to remove link from footer
social:
  name: HMM-UNPAM
  links:
    - https://twitter.com/hmm_unpam
    - https://www.facebook.com/hmm.unpam
    - https://www.linkedin.com/
    - https://plus.google.com/112868886222865383602

disqus:
  shortname: hmm-unpam # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
